### ISSUE TITLE
ColorArea did not change the color when the hex is #000000

### ISSUE THREAD

**Issue by VLarz** [probablykasper/color-picker-svelte#2] opened 2022-08-31 07:48 UTC
![image](https://user-images.githubusercontent.com/46858868/187622477-c87fdaaf-c7e8-461d-bf41-2464419a95bc.png)

**Comment by kasper9n** [comment] 2022-08-31 22:24
Could you elaborate on what the issue is? How do I reproduce it?

**Comment by VLarz** [comment] 2022-09-01 01:28
Hi @probablykasper. Here's the video of this issue 
https://drive.google.com/file/d/1RNUsrMgeNiA5M-sU65t8OLOhTljxJZ7e/view?usp=sharing

**Comment by probablykasper** [comment] 2022-09-01 01:36
That's expected. When you change the hue, the color is still black, so the hex value stays the same

**Comment by kasper9n** [comment] 2022-09-01 01:38
I see, thanks

**Comment by VLarz** [comment] 2022-09-01 16:12
Found what causing it
![image](https://user-images.githubusercontent.com/46858868/187962259-f82e18d6-0d43-4fce-a50d-762847bb9cb4.png)

**Comment by kasper9n** [comment] 2022-09-01 19:59
Good catch, fixed in v0.5.1

**Closed as completed by kasper9n** 2022-09-01 19:59 UTC
